# Generated by Django 5.1.3 on 2024-11-14 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=40)),
                ('Cpno', models.CharField(blank=True, max_length=4, null=True)),
                ('Ccredit', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'constraints': [
                    models.CheckConstraint(check=models.Q(Ccredit__range=(1, 10)), name='course_chk_1'),
                    models.CheckConstraint(check=(models.Q(Cpno__isnull=True) | ~models.Q(Cpno=models.F('Cno'))),
                                           name='course_chk_2')
                ],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=20)),
                ('Ssex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=2, null=True)),
                ('Sage', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('Sdept', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'student',
                'constraints': [
                    models.CheckConstraint(check=models.Q(Sage__gt=0), name='student_chk_1'),
                    models.CheckConstraint(check=models.Q(Ssex__in=['男', '女']), name='student_chk_2')
                ],
            },
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageSystem.course')),
                ('Sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageSystem.student')),
            ],
            options={
                'db_table': 'sc',
                'constraints': [
                    models.CheckConstraint(check=models.Q(Grade__gte=0, Grade__lte=100), name='sc_chk_1'),
                    models.UniqueConstraint(fields=['Sno', 'Cno'], name='uc_student_course')
                ],
                'unique_together': {('Sno', 'Cno')},
            },
        )
    ]
