# Generated by Django 5.1.3 on 2024-11-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Cpno_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='related_courses', to='manageSystem.course'),
        ),
        migrations.AlterField(
            model_name='sc',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manageSystem.course'),
        ),
        migrations.AlterField(
            model_name='sc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manageSystem.student'),
        ),
    ]
