# Generated by Django 5.1.3 on 2024-11-17 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Chours',
            field=models.IntegerField(default=48, validators=[django.core.validators.MinValueValidator(1),
                                                              django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(Chours__range=(1, 99)), name='course_chk_3'),
        ),
    ]
