# Generated by Django 5.1.3 on 2024-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSystem', '0002_alter_sc_course_alter_sc_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc',
            name='Sno',
            field=models.CharField(max_length=20),
        ),
    ]
