# Generated by Django 5.1.3 on 2024-11-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSystem', '0002_course_chours_course_course_chk_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Ccredit',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
