# Generated by Django 5.1.3 on 2024-11-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSystem', '0005_alter_sc_course_alter_sc_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageSystem.course'),
        ),
        migrations.AlterField(
            model_name='sc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageSystem.student'),
        ),
    ]
